# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - master
      - develop
  paths:
    exclude:
    - README.md # This tells the pipeline not to trigger if the only change was made was made to the README.md file regardless of on which branch the change is made.
    - azure*.yml
    - Images/*

variables:
  # rootDir: '.'
  buildDir: 'build'

pool:
  vmImage: 'ubuntu-latest'

steps:

# Download secure file
# Download a secure file to the agent machine
- task: DownloadSecureFile@1
  name: myEnvFile # The name with which to reference the secure file's path on the agent, like $(mySecureFile.secureFilePath)
  displayName: 'Download .env.local'
  inputs:
    secureFile: '.env.local' # The file name or GUID of the secure file

- script: |
    echo "`ls -la`"
    echo download the env.local containing APIkeys
    echo "`cat $(myEnvFile.secureFilePath)`"
    cp $(myEnvFile.secureFilePath) ./.env.local
    echo "`ls -la`"
  displayName: 'Copy .env.local to App root folder'

- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'
- script: |
    npm install
    npm run build
  displayName: 'npm install and build'
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(buildDir)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'